sudo: required
service:
 - docker
before_install:
  - docker build -t angurajmurugesan/travis .
script:
 - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
 - docker images # to verify image is build or not
 - docker push angurajmurugesan/travis
notifications:
 email:
   recipients:
     - anguraj.itech@gmail.com
   on_success: always
   on_failure: always
